// Generated by CoffeeScript 1.6.2
(function() {
  var AudioManager, Event, Simon, SimonUI, delay;

  Event = (function() {
    function Event(name) {
      this.name = name;
      this.listeners = [];
    }

    Event.prototype.subscribe = function(callback) {
      return this.listeners.push(callback);
    };

    Event.prototype.fire = function(obj) {
      var listener, _i, _len, _ref, _results;

      _ref = this.listeners;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        listener = _ref[_i];
        _results.push(listener(obj));
      }
      return _results;
    };

    return Event;

  })();

  AudioManager = (function() {
    var readyCallback;

    readyCallback = null;

    function AudioManager() {
      this.buffers = {};
      this.waitingToLoadCount = 0;
      this.playing = [];
      window.AudioContext = window.AudioContext || window.webkitAudioContext;
      if (AudioContext) {
        this.supported = true;
        this.context = new AudioContext();
      } else {
        this.support = false;
        this.context = null;
        alert("Audio for this game is not supported on your device.");
      }
    }

    AudioManager.prototype.load = function(uri, name) {
      var request, self;

      if (!this.supported) {
        return;
      }
      self = this;
      this.waitingToLoadCount++;
      request = new XMLHttpRequest();
      request.open('GET', uri, true);
      request.responseType = 'arraybuffer';
      request.onload = function() {
        return self.context.decodeAudioData(request.response, function(buffer) {
          self.buffers[name] = buffer;
          self.waitingToLoadCount--;
          return self.checkReady();
        });
      };
      return request.send();
    };

    AudioManager.prototype.play = function(name) {
      var source;

      if (!this.supported) {
        return;
      }
      source = this.context.createBufferSource();
      source.buffer = this.buffers[name];
      source.connect(this.context.destination);
      if (source.start) {
        source.start(0);
      } else {
        source.noteOn(0);
      }
      return this.playing.push([name, source]);
    };

    AudioManager.prototype.stopAll = function() {
      var info, name, source, _i, _len, _ref;

      if (!this.supported) {
        return;
      }
      _ref = this.playing;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        info = _ref[_i];
        name = info[0], source = info[1];
        source.disconnect(0);
      }
      return this.playing = [];
    };

    AudioManager.prototype.stopMatch = function(pattern) {
      var info, name, newPlaying, source, _i, _len, _ref;

      if (!this.supported) {
        return;
      }
      newPlaying = [];
      _ref = this.playing;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        info = _ref[_i];
        name = info[0], source = info[1];
        if (pattern.test(name)) {
          source.disconnect(0);
        } else {
          newPlaying.push(info);
        }
      }
      return this.playing = newPlaying;
    };

    AudioManager.prototype.checkReady = function() {
      if (!this.supported) {
        return;
      }
      if (this.waitingToLoadCount === 0) {
        if (readyCallback) {
          readyCallback();
          return readyCallback = null;
        }
      }
    };

    AudioManager.prototype.ready = function(callback) {
      if (!this.supported) {
        callback();
      }
      readyCallback = callback;
      return this.checkReady();
    };

    return AudioManager;

  })();

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  Simon = (function() {
    function Simon(btnCount) {
      this.btnCount = btnCount;
      this.wrongButton = new Event('wrongButton');
      this.correctButton = new Event('correctButton');
      this.patternComplete = new Event('patternComplete');
      this.pattern = [];
      this.userPattern = [];
    }

    Simon.prototype.start = function() {
      this.pattern = [];
      this.userPattern = [];
      return this.next();
    };

    Simon.prototype.next = function() {
      this.userPattern = [];
      return this.pattern.push(parseInt(Math.random() * this.btnCount));
    };

    Simon.prototype.handleButtonPress = function(btnNum) {
      this.userPattern.push(btnNum);
      if (this.userPattern[this.userPattern.length - 1] === this.pattern[this.userPattern.length - 1]) {
        if (this.userPattern.length === this.pattern.length) {
          this.next();
          return this.patternComplete.fire();
        } else {
          return this.correctButton.fire();
        }
      } else {
        this.wrongButton.fire(this.pattern.length - 1);
        return this.start();
      }
    };

    return Simon;

  })();

  SimonUI = (function() {
    function SimonUI(buttons, game) {
      var button, idx, _i, _len, _ref;

      this.buttons = buttons;
      this.game = game;
      _ref = this.buttons;
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        button = _ref[idx];
        $(button).data('button-num', idx);
      }
      this._initListeners();
      this._loadAudio();
    }

    SimonUI.prototype._initListeners = function() {
      var eventNames, self;

      self = this;
      eventNames = {
        click: 'click',
        mouseDown: 'mousedown',
        mouseUp: 'mouseup'
      };
      if ($('html').hasClass('mobile')) {
        eventNames = {
          click: 'touchstart',
          mouseDown: 'touchstart',
          mouseUp: 'touchend'
        };
      }
      this.buttons.on(eventNames.click, function(evt) {
        var btnNum;

        evt.preventDefault();
        btnNum = $(this).data('button-num');
        return self.game.handleButtonPress(btnNum);
      });
      this.buttons.on(eventNames.mouseDown, function() {
        var btnNum;

        $(this).addClass('active');
        btnNum = $(this).data('button-num');
        return self.playSound(btnNum);
      });
      this.buttons.on(eventNames.mouseUp, function() {
        var btnNum;

        $('.active').removeClass('active');
        btnNum = $(this).data('button-num');
        return self.stopSound();
      });
      this.game.wrongButton.subscribe(function(numRounds) {
        return self.handleWrongButton(numRounds);
      });
      return this.game.patternComplete.subscribe(function() {
        return self.handlePatternComplete();
      });
    };

    SimonUI.prototype._loadAudio = function() {
      var btnNum, button, _i, _len, _ref;

      this.audioManager = new AudioManager();
      _ref = this.buttons;
      for (btnNum = _i = 0, _len = _ref.length; _i < _len; btnNum = ++_i) {
        button = _ref[btnNum];
        this.audioManager.load(this._getSoundUri(btnNum), btnNum);
      }
      return this.audioManager.load(this._getSoundUri('wrong'), 'wrong');
    };

    SimonUI.prototype._getSoundUri = function(name) {
      return "sounds/" + name + ".wav";
    };

    SimonUI.prototype.start = function() {
      var self;

      self = this;
      return this.audioManager.ready(function() {
        self.game.start();
        return self.demoPattern(self.game.pattern);
      });
    };

    SimonUI.prototype.handleButtonPress = function(btnNum) {
      return this.game.handleButtonPress(btnNum);
    };

    SimonUI.prototype.handleWrongButton = function(numRounds) {
      this.stopSound();
      this.playSound('wrong');
      return delay(200, function() {
        $('.num-rounds').html(numRounds);
        return $('.game-over').show();
      });
    };

    SimonUI.prototype.handlePatternComplete = function() {
      return this.demoPattern(this.game.pattern);
    };

    SimonUI.prototype.demoPattern = function(pattern) {
      var doIt, self;

      self = this;
      doIt = function(patternCopy) {
        return self.simulateButton(patternCopy.shift(), function() {
          if (patternCopy.length) {
            return delay(200, function() {
              return doIt(patternCopy);
            });
          }
        });
      };
      return delay(1000, function() {
        return doIt(pattern.slice(0));
      });
    };

    SimonUI.prototype.simulateButton = function(btnNum, callback) {
      var $btn;

      $btn = $(this.buttons[btnNum]);
      $btn.addClass('active');
      this.playSound(btnNum);
      return delay(500, function() {
        $btn.removeClass('active');
        return callback();
      });
    };

    SimonUI.prototype.playSound = function(btnNum) {
      return this.audioManager.play(btnNum);
    };

    SimonUI.prototype.stopSound = function() {
      var self;

      self = this;
      return delay(100, function() {
        return self.audioManager.stopMatch(/\d/);
      });
    };

    return SimonUI;

  })();

  $(function() {
    var $buttons, simon, simonUI;

    $('.simon-buttons').css('height', window.innerHeight + 'px');
    $buttons = $('.simon-button');
    simon = new Simon($buttons.length);
    simonUI = new SimonUI($buttons, simon);
    return $('.start').on('click', function() {
      $(this).closest('.dialog').hide();
      return simonUI.start();
    });
  });

}).call(this);
